### ISSUE TITLE
getDailyWordCount	SyntaxError: Empty JSON string (line 357, file "Code")	

### ISSUE THREAD

**Issue by lsolesen** [jamietr1/google-docs-writing-tracker#28]
I had the script working correctly for 7 days. Suddenly, I am experiencing this error. Anybody else encountered this?

**Comment by jamietr1** [comment]
I've seen this happen when RescueTime's server is not available and therefore returns an empty JSON string. I have a version that fixes this particular issue so that the entire script doesn't fail. I thought I'd pushed it into the master branch, but it looks like I haven't. I'll push this fix out as soon as I get a chance.

**Comment by lsolesen** [comment]
That would be great, as it has started happening every night at the moment when being in ECT +1 timezone.

**Comment by lsolesen** [comment]
Fixed ind the newest version.
